"""Pydantic request / response schemas."""

from app.schemas.address import AddressCreateIn, AddressOut, AddressUpdateIn
from app.schemas.admin import AdminLoginIn, AdminMeOut, AdminOut
from app.schemas.auth import (
    ForgotPasswordIn,
    LogoutIn,
    RefreshIn,
    ResetPasswordIn,
    TokenPairOut,
    UserAuthOut,
    UserBrief,
    UserLoginIn,
    UserRegisterIn,
)
from app.schemas.cart import (
    CartAddIn,
    CartBatchDeleteIn,
    CartGroupOut,
    CartItemOut,
    CartResponseOut,
    CartSelectAllIn,
    CartShopBrief,
    CartSkuBrief,
    CartSpuBrief,
    CartUpdateIn,
)
from app.schemas.catalog import (
    BrandBriefOut,
    BrandCreateIn,
    BrandOut,
    BrandUpdateIn,
    CategoryBriefOut,
    CategoryCreateIn,
    CategoryOut,
    CategoryPathNode,
    CategoryTreeOut,
    CategoryUpdateIn,
)
from app.schemas.common import OkModel, PaginatedOut, PaginationIn
from app.schemas.inventory import InventoryAdjustIn, InventoryLogOut
from app.schemas.merchant import (
    MerchantAccountOut,
    MerchantAccountWithPasswordOut,
    MerchantChangePasswordIn,
    MerchantLoginIn,
    MerchantMeOut,
    ShopOut,
    ShopUpdateIn,
)
from app.schemas.merchant_application import (
    MerchantApplicationCreateIn,
    MerchantApplicationListQuery,
    MerchantApplicationOut,
    MerchantApplicationReviewIn,
)
from app.schemas.order import (
    OrderCancelIn,
    OrderCreatedItem,
    OrderCreateIn,
    OrderCreateOut,
    OrderDetailOut,
    OrderItemOut,
    OrderListItemOut,
    OrderNoteIn,
    OrderPreviewGroupOut,
    OrderPreviewIn,
    OrderPreviewOut,
    OrderPreviewWarning,
    OrderStatusHistoryOut,
    PaymentSessionBriefOut,
    ShipmentEventOut,
)
from app.schemas.payment import PayCreateIn, PaymentAmountOnlyOut, PaymentSessionOut
from app.schemas.product import (
    ShopBriefOut,
    SPUCreateIn,
    SPUDetailOut,
    SPUListItemOut,
    SPUOut,
    SPUReviewIn,
    SPUUpdateIn,
)
from app.schemas.shipment import LogisticsSimulateIn, ShipIn
from app.schemas.sku import SKUCreateIn, SKUOut, SKUUpdateIn
from app.schemas.stats import AdminOrderOverviewOut, MerchantOrderStatsOut
from app.schemas.upload import PresignIn, PresignOut, UploadPurpose
from app.schemas.user import ChangePasswordIn, UserMeOut, UserOut, UserUpdateIn

__all__ = [
    "AddressCreateIn",
    "AddressOut",
    "AddressUpdateIn",
    "AdminLoginIn",
    "AdminMeOut",
    "AdminOrderOverviewOut",
    "AdminOut",
    "BrandBriefOut",
    "BrandCreateIn",
    "BrandOut",
    "BrandUpdateIn",
    "CartAddIn",
    "CartBatchDeleteIn",
    "CartGroupOut",
    "CartItemOut",
    "CartResponseOut",
    "CartSelectAllIn",
    "CartShopBrief",
    "CartSkuBrief",
    "CartSpuBrief",
    "CartUpdateIn",
    "CategoryBriefOut",
    "CategoryCreateIn",
    "CategoryOut",
    "CategoryPathNode",
    "CategoryTreeOut",
    "CategoryUpdateIn",
    "ChangePasswordIn",
    "ForgotPasswordIn",
    "InventoryAdjustIn",
    "InventoryLogOut",
    "LogisticsSimulateIn",
    "LogoutIn",
    "MerchantAccountOut",
    "MerchantAccountWithPasswordOut",
    "MerchantApplicationCreateIn",
    "MerchantApplicationListQuery",
    "MerchantApplicationOut",
    "MerchantApplicationReviewIn",
    "MerchantChangePasswordIn",
    "MerchantLoginIn",
    "MerchantMeOut",
    "MerchantOrderStatsOut",
    "OkModel",
    "OrderCancelIn",
    "OrderCreateIn",
    "OrderCreateOut",
    "OrderCreatedItem",
    "OrderDetailOut",
    "OrderItemOut",
    "OrderListItemOut",
    "OrderNoteIn",
    "OrderPreviewGroupOut",
    "OrderPreviewIn",
    "OrderPreviewOut",
    "OrderPreviewWarning",
    "OrderStatusHistoryOut",
    "PaginatedOut",
    "PaginationIn",
    "PayCreateIn",
    "PaymentAmountOnlyOut",
    "PaymentSessionBriefOut",
    "PaymentSessionOut",
    "PresignIn",
    "PresignOut",
    "RefreshIn",
    "ResetPasswordIn",
    "SKUCreateIn",
    "SKUOut",
    "SKUUpdateIn",
    "SPUCreateIn",
    "SPUDetailOut",
    "SPUListItemOut",
    "SPUOut",
    "SPUReviewIn",
    "SPUUpdateIn",
    "ShipIn",
    "ShipmentEventOut",
    "ShopBriefOut",
    "ShopOut",
    "ShopUpdateIn",
    "TokenPairOut",
    "UploadPurpose",
    "UserAuthOut",
    "UserBrief",
    "UserLoginIn",
    "UserMeOut",
    "UserOut",
    "UserRegisterIn",
    "UserUpdateIn",
]
