"""Pydantic request / response schemas."""

from app.schemas.admin import AdminLoginIn, AdminMeOut, AdminOut
from app.schemas.auth import (
    ForgotPasswordIn,
    LogoutIn,
    RefreshIn,
    ResetPasswordIn,
    TokenPairOut,
    UserAuthOut,
    UserBrief,
    UserLoginIn,
    UserRegisterIn,
)
from app.schemas.catalog import (
    BrandBriefOut,
    BrandCreateIn,
    BrandOut,
    BrandUpdateIn,
    CategoryBriefOut,
    CategoryCreateIn,
    CategoryOut,
    CategoryPathNode,
    CategoryTreeOut,
    CategoryUpdateIn,
)
from app.schemas.common import OkModel, PaginatedOut, PaginationIn
from app.schemas.inventory import InventoryAdjustIn, InventoryLogOut
from app.schemas.merchant import (
    MerchantAccountOut,
    MerchantAccountWithPasswordOut,
    MerchantChangePasswordIn,
    MerchantLoginIn,
    MerchantMeOut,
    ShopOut,
    ShopUpdateIn,
)
from app.schemas.merchant_application import (
    MerchantApplicationCreateIn,
    MerchantApplicationListQuery,
    MerchantApplicationOut,
    MerchantApplicationReviewIn,
)
from app.schemas.product import (
    ShopBriefOut,
    SPUCreateIn,
    SPUDetailOut,
    SPUListItemOut,
    SPUOut,
    SPUReviewIn,
    SPUUpdateIn,
)
from app.schemas.sku import SKUCreateIn, SKUOut, SKUUpdateIn
from app.schemas.upload import PresignIn, PresignOut, UploadPurpose
from app.schemas.user import ChangePasswordIn, UserMeOut, UserOut, UserUpdateIn

__all__ = [
    "AdminLoginIn",
    "AdminMeOut",
    "AdminOut",
    "BrandBriefOut",
    "BrandCreateIn",
    "BrandOut",
    "BrandUpdateIn",
    "CategoryBriefOut",
    "CategoryCreateIn",
    "CategoryOut",
    "CategoryPathNode",
    "CategoryTreeOut",
    "CategoryUpdateIn",
    "ChangePasswordIn",
    "ForgotPasswordIn",
    "InventoryAdjustIn",
    "InventoryLogOut",
    "LogoutIn",
    "MerchantAccountOut",
    "MerchantAccountWithPasswordOut",
    "MerchantApplicationCreateIn",
    "MerchantApplicationListQuery",
    "MerchantApplicationOut",
    "MerchantApplicationReviewIn",
    "MerchantChangePasswordIn",
    "MerchantLoginIn",
    "MerchantMeOut",
    "OkModel",
    "PaginatedOut",
    "PaginationIn",
    "PresignIn",
    "PresignOut",
    "RefreshIn",
    "ResetPasswordIn",
    "SKUCreateIn",
    "SKUOut",
    "SKUUpdateIn",
    "SPUCreateIn",
    "SPUDetailOut",
    "SPUListItemOut",
    "SPUOut",
    "SPUReviewIn",
    "SPUUpdateIn",
    "ShopBriefOut",
    "ShopOut",
    "ShopUpdateIn",
    "TokenPairOut",
    "UploadPurpose",
    "UserAuthOut",
    "UserBrief",
    "UserLoginIn",
    "UserMeOut",
    "UserOut",
    "UserRegisterIn",
    "UserUpdateIn",
]
