# Project-wide Gradle settings for JDCloneApp.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# Enables the Gradle configuration cache to speed up subsequent builds.
org.gradle.configuration-cache=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK.
android.useAndroidX=true

# Non-transitive R classes reduce build times and APK size.
android.nonTransitiveRClass=true

# Kotlin code style for this project.
kotlin.code.style=official
